### ISSUE TITLE
Probably incorrect kgt format for SDF applications

### ISSUE THREAD

**Issue by BeethovenKodar** [forsyde/forsyde-io#20]
Bold of me to make an issue this early into the project, but I think there might be an issue actually B) 

This is the simple code snippet I use
```java
SystemGraph sGraph = new SystemGraph();

SDFActorViewer a = SDFActor.enforce(sGraph, sGraph.newVertex("Actor A"));
a.consumption(Map.of("s_in", 2));
a.production(Map.of("s1", 2));
a.addPorts("s_in", "s1");
Visualizable.enforce(a);

SDFActorViewer b = SDFActor.enforce(sGraph, sGraph.newVertex("Actor B"));
b.consumption(Map.of("s1", 3));
b.production(Map.of("s_out", 1));
b.addPorts("s1", "s_out");
Visualizable.enforce(b);

SDFChannelViewer ab_chan = SDFChannel.enforce(sGraph, sGraph.newVertex("Channel A-B"));
ab_chan.numInitialTokens(0);
sGraph.connect(
    a, 
    ab_chan,
    EdgeTraits.SDFNetworkEdge, 
    EdgeTraits.VisualConnection
);
sGraph.connect(
    ab_chan,
    b, 
    EdgeTraits.SDFNetworkEdge, 
    EdgeTraits.VisualConnection
);
Visualizable.enforce(ab_chan);

return sGraph;
```
This produces the following `.kgt` file which gives syntax errors in VSCode:
```
1  knode forsyde {
2     klabel "ForSyDe Model"
3     knode v_Channel A-B {
4       klabel "Channel A-B [SDFChannel, MoCEntity]"
5       kedge (  -> v_Actor_B)
6     }
7     knode v_Actor B {
8       klabel "Actor B [SDFActor, MoCEntity]"
9     }
10   knode v_Actor A {
11     klabel "Actor A [SDFActor, MoCEntity]"
12     kedge (  -> v_Channel_A-B)
13   }
14 }
```
There are two things that I believe have to be corrected.
- Line 3, 7, 10: The kgt syntax does not allow node names to include spaces. Line 12 handles this case by inserting an underscore, so it's not consistent. Additionally, this makes the edge of the channel not recognized since they're written differently.
- Hyphens are not allowed in a knode name and naming a `Vertex` allows this. I suggest to either replace the hyphen by some underscore or throw an error.
-

**Comment by Rojods** [comment]
Well, bold you actually found an actual bug! This will have to be connected in the bridge to KGT because the common model AKA System graphs do have full support for spaces etc. I come back to this issue once it is fixed.

**Comment by Rojods** [comment]
@BeethovenKodar could you try out the same file now with release 0.7.18?

**Comment by BeethovenKodar** [comment]
It works nicely with the new version. The vertex (KGT node) name changes from `Actor A` to `Actor_space_A` and the KGT file can be viewed normally :) You can surely close this issue!
